//produit
###
POST http://localhost:3315/api/ajout/produit
Content-Type: application/json

{
  "designation": "banane",
  "user_id": "16",
  "type_id": "6",
  "genre_id": "5",
  "quantite": "6"
}

###
GET http://localhost:3315/api/produits/17

###
GET http://localhost:3315/api/produit/24

###
PUT http://localhost:3315/api/modifi/produit/26
Content-Type: application/json

{
  "designation": "evian",
  "user_id": "3",
  "type_id": "6",
  "genre_id": "5",
  "quantite": "12"
}

###
DELETE http://localhost:3315/api/supprime/produit/8
Content-Type: application/json


###
GET http://localhost:3315/api/typegenre

###


//shopping list
GET http://localhost:3315/api/affiche/shoppingList/17
Content-Type: application/json

###
POST http://localhost:3315/api/shopping-list
Content-Type: application/json

{
  "designation": "sardine",
  "user_id": "15",
  "type_id": "6",
  "genre_id": "5",
  "quantite": "1"
}

###
POST http://localhost:3315/api/shopping-list/validate/2
Content-Type: application/json

###
DELETE http://localhost:3315/api/delete/shoppingList/7
Content-Type: application/json