POST http://localhost:3315/api/user
Content-Type: application/json

{
  "firstname": "Sow",
  "lastname": "Aliou",
  "email": "aliou@example.com",
  "password": "mypassword797",
  "birth_day": "2006-08-11"
}

###
GET http://localhost:3315/api/user/profile/17
Content-Type: application/json

###
PUT http://localhost:3315/api/user/update/18
Content-Type: application/json

{
  "firstname": "",
  "lastname": "",
  "email": "salem3@gmail.com.com",
  "password": "",
  "birth_day": ""
}

###
DELETE http://localhost:3315/api/user/delete/2
Content-Type: application/json